### ISSUE TITLE
PLC support?

### ISSUE THREAD

**Issue by alecjacobson** [MarcoAttene/CDT#11]
I've had good experiences with this code so far for meshing sets of points and triangles. The readme and paper mention support for PLC, that would include floating/dangling edges (line segments). Does this code support that? How can I input collections of edges?

**Comment by MarcoAttene** [comment]
The algorithm should work with no changes, but the creation of such an input is not directly supported in the code. If you wish, you may try tweaking the code by appending your dangling edges to Steiner_plc in main.cpp, on line 64, right before starting the segment recovery.

**Comment by alecjacobson** [comment]
Awesome! Thanks.

**Comment by alecjacobson** [comment]
With all the reindexing it wasn't completely trivial, but I think I got it right in my fork:

https://github.com/alecjacobson/CDT

I read in the edges from .obj files.

**Comment by yig** [comment]
It would still error without any faces. I modified it so you don't have to pass any faces:

https://github.com/yig/CDT
