### ISSUE TITLE
How to visualize the .mesh file

### ISSUE THREAD

**Issue by RainSureZhao** [MarcoAttene/CDT#12]
How can I visualize a medit file? I used TetView software for visualization, but I can't see any results. However, I can see the results when using the .mesh format file generated by Tetgen. Do I need to do any additional steps?
![image](https://github.com/user-attachments/assets/3780570e-6e87-4fce-853e-b951995c495b)

**Comment by MarcoAttene** [comment]
I successfully use Bruno Levy's Graphite to view MEDIT files produced by CDT. You may download it here:
https://github.com/BrunoLevy/GraphiteThree
