### ISSUE TITLE
How to display the off.set file？

### ISSUE THREAD

**Issue by WHUT666** [MarcoAttene/CDT#2]
How to display the off.set file？Can you provide some suggestions or convert this file to a more general format？

**Comment by WHUT666** [comment]
![image](https://github.com/MarcoAttene/CDT/assets/38042728/2373a4bb-2cd8-4ba5-b9ba-37ed01910ba5)I ended up with a mesh like this, is this correct and how can I get a better mesh if used for CFD

**Comment by MarcoAttene** [comment]
This is correct. Please consider that CDT is not meant to produce optimized meshes suitable for CFD. You may need to save the tetrahedral mesh and optimize it afterwards using another tool such as tetgen (https://wias-berlin.de/software/tetgen/) or mmg3d (https://www.mmgtools.org/)
