### ISSUE TITLE
Symbolic perturbation failed

### ISSUE THREAD

**Issue by FantasyVR** [MarcoAttene/CDT#3]
When I use [this](https://ten-thousand-models.appspot.com/detail.html?file_id=40923) mesh as input, I get errors below:

```
$./cdt roy.off
Symbolic perturbation failed! Should not happen.
```

The format of the original mesh is `.stl`, I imported it in MeshLab and exported it as a `.off` file.

**Comment by MarcoAttene** [comment]
That happens because the model has self-intersections. CDT is not supposed to work on these invalid models.
