### ISSUE TITLE
How to get a better result?

### ISSUE THREAD

**Issue by jiayaozhang** [MarcoAttene/CDT#5]
Thanks for your great work!

I was trying to generate by

` .\cdt.exe -m .\boeing_part.off`

![image](https://github.com/MarcoAttene/CDT/assets/38579506/50936007-9197-4d82-b949-79c77d2ff165)

But the output tetrahedral mesh looks far away from the original mesh appearance
How can i generate better result in `.mesh` formats then? Many thanks!

**Comment by MarcoAttene** [comment]
That's becuase you are keeping all the tetrahedra within the covex hull. Use the -r switch if you wish to keep inner tets only. You may launch cdt without arguments to see a list of possible options.
